---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jeffross/cms-api.jeff-rossi.com
    - export SHAREDPATH=/home/jeffross/shared/node_modules
    - /bin/npm i --production
    - /bin/npm run build
    - /bin/cp ormconfig.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -r dist $DEPLOYPATH
    - /bin/cp -rn node_modules/* $SHAREDPATH
    - /bin/ln -s $SHAREDPATH "$DEPLOYPATH/node_modules"
    - /bin/rm -rf node_modules
    - /bin/rm -rf dist/*